### ISSUE TITLE
Infinite Health

### ISSUE THREAD

**Issue by Daria40K** [websitenmaker12/Advanced-Genetics#122]
In the Modpack Yogcast Complete Pack (2.8.7.3), if you try to remove an ability it doesn't work until you try to remove it again. But instead of trying to remove it again you re-add the More Health ability it adds more health on top of what was already there.

**Comment by Slind14** [comment]
"I discovered a glitch with the Health Gene from Iron Golems. I believe that when using the Gene and the Anti-gene while having Tinkers' Construct Health Cans equipped, instead of removing the Health Gene the Anit-gene instead increases the players health and then allows the player to use the regular gene again thus creating an endless cycle always increasing the players health."

**Comment by websitenmaker12** [comment]
Fixed in the next version.

**Comment by Slind14** [comment]
:)
