### ISSUE TITLE
Crash on blood withdrawal attempt.

### ISSUE THREAD

**Issue by blaisen** [websitenmaker12/Advanced-Genetics#21]
http://pastebin.com/P4C300U2

I filled three syringes with my own blood successfully, but on attempting to fill the fourth, I crashed, reason bad packet ID 120. I tried to reconnect to the server, and my client crashed again and exited of its own accord. I had to use an NBT editor to remove the item from my inventory, whereupon I could reconnect to the server. I tried again with another empty syringe, and crashed, reason bad packet ID 116. Tried again to reconnect, and crashed again, and once more, my client exited of its own accord. According to the server log, the first crash was a disconnect.genericReason, and the second was a disconnect.endOfStream. Any further information may be available upon request.

**Comment by websitenmaker12** [comment]
Is it possible that you have posted the wrong crashlog because the log has nothing to do with Advanced Genetics?

**Comment by blaisen** [comment]
No, that's the correct one. >_> Three sixteen PM. I'll reproduce the error and send the new crashlog if you like.

Method: Filled three syringes in succession. On release of right mouse button for third syringe, disconnected.
Disconnect Reason: Internal Exception: java.io.IOException: Bad packet ID 88 (serverside: disconnect.genericReason)
Attempt to reconnect: End of Stream (serverside: disconnect.endOfStream. Server still functioning properly for other users.)
No crash log generated whatsoever this time because the client hasn't actually crashed or closed. However, I still have to use an NBT editor to remove that third syringe from my inventory, serverside, in order to successfully reconnect to the server.

EDIT: Tried again to reconnect, this time the client DID crash and exit.

Crashlog: http://pastebin.com/tQzADgpu

**Comment by blaisen** [comment]
Here, I repeated the process again, and recorded it for you, in case I'm not explaining it properly... Happened with just the first syringe this time, though I had two already filled in my inventory. (The third you see in the video has already been centrifuged.) Apologies if it's too much info or contains extraneous detail, but I wanted to make sure you knew everything you could possibly need to know.

Link to recording: https://www.youtube.com/watch?v=dWZsM1LXy4g

Crashlog: http://pastebin.com/K5JvbcAT

EDIT: Wow, that is... remarkably bad video quality... Apologies for that. If there's anything you can't read, let me know.

**Comment by websitenmaker12** [comment]
Ok. Thanks. Now I understand what you mean. But as I said. It seams that this isn't a bug of AdvancedGenetics because something went terrible wrong in some ChickenbonesUntil-Classes so I don't really know where the problem is. It may take a while before I can fix this "bug".

Anyway, thank you very much.

**Comment by BlackAce21** [comment]
I can answer this problem for you, we had this happen on our beta testing server for monster, we are running a public server for testing the new mod pack and upon inspection of the player.dat files involved we found that your code is copying the entire player.dat information (including all forge and bukkit location data in MCPC and i do mean EVERYTHING) and storing it inside that blood syringe item. This is not good as servers running both bukkit and forge will not be able to create more then a few blood syringes without maxing out their player.dat files with too much information for the server to process, it ends up crashing their client and they cant log back in until the syringes have been totally removed from their player files. (We have a lot of people highly versed in NBT editing) This could probably be fixed by having your code target only specific information from the player file and perhaps adding a way of targeting those specific details for the player so they have to draw blood for that specific trait only.
